// backend/controllers/memberControllerMongo.js
const Member = require('../models/MemberMongo');
const Admin = require('../models/AdminMongo');
const { generateMembershipId } = require('../config/database-mongo');

// Get all members
const getMembers = async (req, res) => {
    try {
        const { search, status, page = 1, limit = 20 } = req.query;
        const filter = {};
        
        if (search) {
            filter.$or = [
                { membership_id: { $regex: search, $options: 'i' } },
                { full_name: { $regex: search, $options: 'i' } },
                { phone_call: { $regex: search, $options: 'i' } },
                { email: { $regex: search, $options: 'i' } }
            ];
        }
        
        if (status) {
            filter.status = status;
        }
        
        const skip = (parseInt(page) - 1) * parseInt(limit);
        const limitNum = parseInt(limit);
        
        const [members, total] = await Promise.all([
            Member.find(filter)
                .populate('approved_by', 'full_name username')
                .sort({ created_at: -1 })
                .skip(skip)
                .limit(limitNum),
            Member.countDocuments(filter)
        ]);
        
        res.json({
            members,
            pagination: {
                total,
                page: parseInt(page),
                limit: limitNum,
                pages: Math.ceil(total / limitNum)
            }
        });
    } catch (error) {
        console.error('Get members error:', error.message);
        res.status(500).json({ error: 'Server error' });
    }
};

// Get single member
const getMember = async (req, res) => {
    try {
        const member = await Member.findById(req.params.id)
            .populate('approved_by', 'full_name username');
        
        if (!member) {
            return res.status(404).json({ error: 'Member not found' });
        }
        
        res.json({ member });
    } catch (error) {
        console.error('Get member error:', error.message);
        res.status(500).json({ error: 'Server error' });
    }
};

// Create member
const createMember = async (req, res) => {
    try {
        const memberData = req.body;
        console.log('📝 Creating member with data:', memberData);
        
        let membership_id = memberData.membership_id;
        
        if (membership_id && membership_id.trim() !== '') {
            membership_id = membership_id.trim();
            const existing = await Member.findOne({ membership_id });
            if (existing) {
                return res.status(400).json({ 
                    error: 'Membership ID already exists. Please use a different ID or leave empty for auto-generation.' 
                });
            }
        } else {
            membership_id = await generateMembershipId(Member);
            console.log('📝 Auto-generated membership ID:', membership_id);
        }
        
        // Handle 'Other' instrument
        let instrument = memberData.instrument;
        if (instrument === 'Other' && memberData.other_instrument) {
            instrument = memberData.other_instrument;
        }
        
        let approved_by = null;
        if (memberData.status === 'approved') {
            approved_by = req.adminId || null;
        }
        
        const member = new Member({
            membership_id,
            full_name: memberData.full_name,
            date_of_birth: memberData.date_of_birth,
            gender: memberData.gender,
            nationality: memberData.nationality,
            phone_call: memberData.phone_call,
            whatsapp: memberData.whatsapp,
            email: memberData.email || null,
            digital_address: memberData.digital_address || null,
            institution: memberData.institution || null,
            level_program: memberData.level_program || null,
            occupation: memberData.occupation || null,
            instrument: instrument,
            other_instrument: memberData.other_instrument || null,
            years_experience: memberData.years_experience || 0,
            previous_band: memberData.previous_band || null,
            reason_joining: memberData.reason_joining || null,
            emergency_name: memberData.emergency_name,
            emergency_relationship: memberData.emergency_relationship,
            emergency_phone: memberData.emergency_phone,
            date_received: memberData.date_received,
            approved_by: approved_by,
            status: memberData.status || 'pending'
        });
        
        await member.save();
        console.log('✅ Member created with ID:', member.membership_id);
        
        res.status(201).json({
            message: 'Member created successfully',
            member,
            autoGenerated: !memberData.membership_id || memberData.membership_id.trim() === ''
        });
    } catch (error) {
        console.error('❌ Create member error:', error.message);
        if (error.code === 11000) {
            return res.status(400).json({ 
                error: 'Membership ID already exists. Please use a different ID or leave empty for auto-generation.' 
            });
        }
        res.status(500).json({ error: 'Server error: ' + error.message });
    }
};

// Update member
const updateMember = async (req, res) => {
    try {
        const { id } = req.params;
        const updateData = req.body;
        
        delete updateData.membership_id;
        
        if (Object.keys(updateData).length === 0) {
            return res.status(400).json({ error: 'No fields to update' });
        }
        
        const member = await Member.findByIdAndUpdate(
            id,
            { ...updateData, updated_at: new Date() },
            { new: true, runValidators: true }
        );
        
        if (!member) {
            return res.status(404).json({ error: 'Member not found' });
        }
        
        res.json({
            message: 'Member updated successfully',
            member
        });
    } catch (error) {
        console.error('Update member error:', error.message);
        res.status(500).json({ error: 'Server error' });
    }
};

// Delete member
const deleteMember = async (req, res) => {
    try {
        const { id } = req.params;
        const member = await Member.findById(id);
        
        if (!member) {
            return res.status(404).json({ error: 'Member not found' });
        }
        
        const memberInfo = {
            membership_id: member.membership_id,
            full_name: member.full_name
        };
        
        await member.deleteOne();
        
        res.json({
            message: 'Member deleted successfully',
            deleted_member: memberInfo
        });
    } catch (error) {
        console.error('Delete member error:', error.message);
        res.status(500).json({ error: 'Server error' });
    }
};

// Get member statistics
const getMemberStats = async (req, res) => {
    try {
        const [total, male, female, pending, approved, rejected] = await Promise.all([
            Member.countDocuments(),
            Member.countDocuments({ gender: 'Male' }),
            Member.countDocuments({ gender: 'Female' }),
            Member.countDocuments({ status: 'pending' }),
            Member.countDocuments({ status: 'approved' }),
            Member.countDocuments({ status: 'rejected' })
        ]);
        
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const todayRegistrations = await Member.countDocuments({
            created_at: { $gte: today }
        });
        
        res.json({
            stats: {
                total: total || 0,
                male: male || 0,
                female: female || 0,
                pending: pending || 0,
                approved: approved || 0,
                rejected: rejected || 0,
                today_registrations: todayRegistrations || 0
            }
        });
    } catch (error) {
        console.error('Get member stats error:', error.message);
        res.status(500).json({ error: 'Server error' });
    }
};

module.exports = {
    getMembers,
    getMember,
    createMember,
    updateMember,
    deleteMember,
    getMemberStats
};